### ISSUE TITLE
Move Webslice plasmoid from deprecated Qt WebKit to Qt WebEngine

### ISSUE THREAD

**Issue by MurzNN** [Cqoicebordel/webslice-plasmoid#8]
Seems that in Qt 5.6 Qt WebKit is a deprecated module:
https://wiki.qt.io/New_Features_in_Qt_5.6#Deprecated_Modules
Can you try to port your Plasmoid to Qt WebEngine? Maybe it solve other issues?

**Comment by MurzNN** [comment]
Seems that in KDE 5.13 most web browser problems was solved: https://bugs.kde.org/show_bug.cgi?id=371023
Does your plasmoid also will move to new technology in KDE 5.13?

**Comment by Cqoicebordel** [comment]
I didn't switch from QtWebkit to QtWebEngine. The module is supposed to be deprecated and deleted from the releases, but it seems it's still present. Maybe it's only the full Qt modules, and not the QtQuick ones.

In any case, a change to QtWebEngine seems necessary in the long term. But it needs a lots of rewrite, and I'm not sure I'm up to it right now.
I think that as long as that plasmoid works, there is no need to rewrite things. So, we'll see.

**Comment by Cqoicebordel** [comment]
Finally done it !
Took me a while to start, and a while to do...
